version: "3.9"

services:
  web:
    build: .
    container_name: news_app
    restart: always
    logging:
      options:
        max-size: "5m"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
    # change example.com with your domain
      VIRTUAL_HOST: example.com
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: example.com
volumes:
      news_app:
networks:
  default:
    external:
      name: nginx-proxy
