# Generated by Django 4.1 on 2022-08-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_news_add_time_jalali'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='add_time_jalali',
        ),
    ]
