# Generated by Django 4.1 on 2022-08-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_contact_email_alter_contact_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
    ]
