# Generated by Django 4.1 on 2022-08-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_contact_contactmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='Contact',
        ),
    ]
